# Generated by Django 5.1.2 on 2024-10-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0001_initial'),
        ('apis_metainfo', '0014_remove_uri_domain_remove_uri_loaded_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='LivesIn',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            bases=('relations.relation',),
        ),
        migrations.CreateModel(
            name='WorksIn',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
            ],
            bases=('relations.relation',),
        ),
        migrations.RemoveField(
            model_name='institution',
            name='id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.RemoveField(
            model_name='place',
            name='id',
        ),
        migrations.AddField(
            model_name='institution',
            name='rootobject_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='person',
            name='rootobject_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='rootobject_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versioninstitution',
            name='rootobject_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject'),
        ),
        migrations.AddField(
            model_name='versioninstitution',
            name='self_contenttype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='rootobject_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='self_contenttype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='versionplace',
            name='rootobject_ptr',
            field=models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject'),
        ),
        migrations.AddField(
            model_name='versionplace',
            name='self_contenttype',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
