# Generated by Django 5.1.2 on 2024-11-19 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0002_islearningat'),
        ('apis_metainfo', '0014_remove_uri_domain_remove_uri_loaded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('data', models.JSONField(editable=False, null=True)),
                ('image', models.TextField(editable=False, max_length=512)),
                ('issue', models.TextField(editable=False, max_length=256)),
                ('lst_task_id', models.IntegerField(editable=False)),
                ('lst_annotation_id', models.IntegerField(editable=False)),
                ('lst_result_id', models.TextField(editable=False, max_length=128)),
            ],
            options={
                'unique_together': {('lst_task_id', 'lst_annotation_id', 'lst_result_id')},
            },
            bases=('apis_metainfo.rootobject',),
        ),
    ]
