# Generated by Django 5.1.2 on 2024-11-13 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0002_alter_mongodbmodel_content_type_and_more'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaboration',
            new_name='CollaboratesWith',
        ),
    ]
