# Generated by Django 5.1.2 on 2024-11-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0003_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='depicted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
