# Generated by Django 5.1.2 on 2025-01-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0006_annotation_internal_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_death',
        ),
    ]
