# Generated by Django 5.1.2 on 2025-01-10 09:23

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0008_person_date_of_birth_person_date_of_birth_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='islearningat',
            name='from_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='from_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='from_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='from_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='to_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='to_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='to_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='islearningat',
            name='to_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='from_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='from_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='from_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='from_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='to_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='to_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='to_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ismemberof',
            name='to_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='from_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='from_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='from_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='from_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='to_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='to_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='to_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livesin',
            name='to_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
