# Generated by Django 5.1.2 on 2025-01-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0009_islearningat_from_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='biography',
        ),
    ]
