# Generated by Django 5.1.5 on 2025-01-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0012_bornin_diedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
