# Generated by Django 5.1.2 on 2025-02-05 09:14

import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0014_educationtype_islearningat_details_and_more'),
        ('apis_metainfo', '0015_uri_content_type_uri_object_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionType',
            fields=[
                ('rootobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_metainfo.rootobject')),
                ('label', models.CharField(blank=True, default='', max_length=4096, verbose_name='Label')),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_metainfo.rootobject', models.Model),
        ),
        migrations.CreateModel(
            name='WorksAs',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('from_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('to_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('from_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('details', models.CharField(blank=True, default='', max_length=4096, verbose_name='Details')),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.relation', models.Model),
        ),
        migrations.CreateModel(
            name='VersionProfessionType',
            fields=[
                ('rootobject_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('version_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=4096, verbose_name='Label')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('self_contenttype', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'historical profession type',
                'verbose_name_plural': 'historical profession types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
