# Generated by Django 5.1.2 on 2025-02-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0015_professiontype_worksas_versionprofessiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='membership_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='membership_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
