# Generated by Django 5.1.2 on 2025-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0017_specialarea_person_special_areas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='exile_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='party_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='exile_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='party_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
