# Generated by Django 5.1.2 on 2025-02-05 14:24

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0018_person_comment_person_exile_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='inheritance',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='inheritance',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
    ]
