# Generated by Django 5.1.2 on 2025-02-05 15:45

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0019_person_inheritance_versionperson_inheritance'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='other_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='research_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='other_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='research_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
    ]
