# Generated by Django 5.1.2 on 2025-02-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0020_person_other_sources_person_research_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='isinventoriedin',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='isinventoriedin',
            name='extent',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
