# Generated by Django 5.1.2 on 2025-02-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0021_isinventoriedin_contact_isinventoriedin_extent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorksIn',
        ),
    ]
