# Generated by Django 5.1.2 on 2025-02-06 09:25

import django_interval.fields
import django_json_editor_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0022_delete_worksin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='person',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_death',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True, verbose_name='Date of death'),
        ),
        migrations.AlterField(
            model_name='person',
            name='exile_comment',
            field=models.TextField(blank=True, default='', verbose_name='Exile comment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inheritance',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Inheritance'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_comment',
            field=models.TextField(blank=True, default='', verbose_name='Membership comment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Other sources'),
        ),
        migrations.AlterField(
            model_name='person',
            name='party_comment',
            field=models.TextField(blank=True, default='', verbose_name='Party comment'),
        ),
        migrations.AlterField(
            model_name='person',
            name='research_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Research sources'),
        ),
        migrations.AlterField(
            model_name='person',
            name='special_areas',
            field=models.ManyToManyField(blank=True, to='apis_instance_nsvis.specialarea', verbose_name='Special areas'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='citizenship',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Citizenship'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='date_of_birth',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='date_of_death',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True, verbose_name='Date of death'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='exile_comment',
            field=models.TextField(blank=True, default='', verbose_name='Exile comment'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='inheritance',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Inheritance'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='membership_comment',
            field=models.TextField(blank=True, default='', verbose_name='Membership comment'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='other_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Other sources'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='party_comment',
            field=models.TextField(blank=True, default='', verbose_name='Party comment'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='research_sources',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Research sources'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='Name'),
        ),
    ]
