# Generated by Django 5.1.2 on 2025-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0023_alter_person_citizenship_alter_person_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession_comment',
            field=models.TextField(blank=True, default='', verbose_name='Profession comment'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='profession_comment',
            field=models.TextField(blank=True, default='', verbose_name='Profession comment'),
        ),
    ]
