# Generated by Django 5.1.2 on 2025-02-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0024_person_profession_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressdata',
            options={'verbose_name': 'Address Data', 'verbose_name_plural': 'Address Datas'},
        ),
        migrations.AlterModelOptions(
            name='educationtype',
            options={'verbose_name': 'Education Type', 'verbose_name_plural': 'Education Types'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Place', 'verbose_name_plural': 'Places'},
        ),
        migrations.AlterModelOptions(
            name='professiontype',
            options={'verbose_name': 'Profession Type', 'verbose_name_plural': 'Profession Types'},
        ),
        migrations.AlterModelOptions(
            name='specialarea',
            options={'verbose_name': 'Special Area', 'verbose_name_plural': 'Special Areas'},
        ),
        migrations.AlterModelOptions(
            name='versionaddressdata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Address Data', 'verbose_name_plural': 'historical Address Datas'},
        ),
        migrations.AlterModelOptions(
            name='versioneducationtype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Education Type', 'verbose_name_plural': 'historical Education Types'},
        ),
        migrations.AlterModelOptions(
            name='versioninstitution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Institution', 'verbose_name_plural': 'historical Institutions'},
        ),
        migrations.AlterModelOptions(
            name='versionperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Person', 'verbose_name_plural': 'historical Persons'},
        ),
        migrations.AlterModelOptions(
            name='versionplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Place', 'verbose_name_plural': 'historical Places'},
        ),
        migrations.AlterModelOptions(
            name='versionprofessiontype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Profession Type', 'verbose_name_plural': 'historical Profession Types'},
        ),
        migrations.AlterModelOptions(
            name='versionspecialarea',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Special Area', 'verbose_name_plural': 'historical Special Areas'},
        ),
    ]
