# Generated by Django 5.1.2 on 2025-02-06 10:21

import django_json_editor_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0025_alter_addressdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='literature',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Literature'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='literature',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True, verbose_name='Literature'),
        ),
    ]
