# Generated by Django 5.1.2 on 2025-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0026_person_literature_versionperson_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='propaganda_membership',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=9, verbose_name='Member in a propaganda company'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_ban',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=8, verbose_name='Work ban during NS'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_ns',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=9, verbose_name='Worked during NS'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='propaganda_membership',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=9, verbose_name='Member in a propaganda company'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='work_ban',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=8, verbose_name='Work ban during NS'),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='work_ns',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNK', 'Unknown')], default='UNK', max_length=9, verbose_name='Worked during NS'),
        ),
    ]
