# Generated by Django 5.1.2 on 2025-02-11 12:46

import django.db.models.deletion
import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0027_person_propaganda_membership_person_work_ban_and_more'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExileIn',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('from_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('to_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('from_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_to', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('relations.relation', models.Model),
        ),
    ]
