# Generated by Django 5.1.2 on 2025-02-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0028_exilein'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'forename'], 'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
    ]
