# Generated by Django 5.1.2 on 2025-02-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0030_rename_comment_person_address_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_comment',
            field=models.TextField(blank=True, default='', verbose_name='Address Comment'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='address_comment',
            field=models.TextField(blank=True, default='', verbose_name='Address Comment'),
        ),
    ]
