# Generated by Django 5.1.2 on 2025-02-27 10:16

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0031_alter_person_address_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateswith',
            name='from_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='from_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='from_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='from_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='to_date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='to_date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='to_date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='collaborateswith',
            name='to_date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
