# Generated by Django 5.1.2 on 2025-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0032_collaborateswith_from_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=4096, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='', max_length=4096, verbose_name='Gender'),
        ),
    ]
