# Generated by Django 5.1.2 on 2025-03-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0033_alter_person_gender_alter_versionperson_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionaddressdata',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versioneducationtype',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versioninstitution',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionplace',
            name='self_contenttype',
        ),
        migrations.RemoveField(
            model_name='versionprofessiontype',
            name='self_contenttype',
        ),
        migrations.AddField(
            model_name='place',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16),
        ),
        migrations.AddField(
            model_name='versionplace',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html">Geonames Feature Code List</a>', max_length=16),
        ),
    ]
