# Generated by Django 5.1.2 on 2025-03-05 06:09

import apis_instance_nsvis.models
import django.db.models.deletion
import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0034_remove_versionaddressdata_self_contenttype_and_more'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprisonedIn',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('from_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('to_date', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('from_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('from_date_date_to', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_sort', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_from', models.DateField(blank=True, editable=False, null=True)),
                ('to_date_date_to', models.DateField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(apis_instance_nsvis.models.NsvisRelationMixin, 'relations.relation', models.Model),
        ),
    ]
