# Generated by Django 5.1.2 on 2025-03-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0036_isinheritancein'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressInPlace',
            new_name='LocatedIn',
        ),
    ]
