# Generated by Django 5.1.2 on 2025-03-10 11:12

import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0037_rename_addressinplace_locatedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bornin',
            name='date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bornin',
            name='date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bornin',
            name='date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bornin',
            name='date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diedin',
            name='date',
            field=django_interval.fields.FuzzyDateParserField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diedin',
            name='date_date_from',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diedin',
            name='date_date_sort',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='diedin',
            name='date_date_to',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
