# Generated by Django 5.1.2 on 2025-03-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0038_bornin_date_bornin_date_date_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth_date_from',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth_date_sort',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth_date_to',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death_date_from',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death_date_sort',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_of_death_date_to',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_birth_date_from',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_birth_date_sort',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_birth_date_to',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_death_date_from',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_death_date_sort',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='date_of_death_date_to',
        ),
    ]
