# Generated by Django 5.1.7 on 2025-03-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0039_remove_person_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionaddressdata',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='versionaddressdata',
            name='rootobject_ptr',
        ),
        migrations.DeleteModel(
            name='AddressData',
        ),
        migrations.DeleteModel(
            name='VersionAddressData',
        ),
    ]
