# Generated by Django 5.1.7 on 2025-04-04 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0041_alter_bornin_date_date_from_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'verbose_name': 'annotation', 'verbose_name_plural': 'annotations'},
        ),
    ]
