# Generated by Django 5.1.7 on 2025-04-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0042_alter_annotation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtype',
            options={'ordering': ['label'], 'verbose_name': 'Education Type', 'verbose_name_plural': 'Education Types'},
        ),
        migrations.AlterModelOptions(
            name='professiontype',
            options={'ordering': ['label'], 'verbose_name': 'Profession Type', 'verbose_name_plural': 'Profession Types'},
        ),
        migrations.AlterModelOptions(
            name='specialarea',
            options={'ordering': ['label'], 'verbose_name': 'Special Area', 'verbose_name_plural': 'Special Areas'},
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='professiontype',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='specialarea',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='versioneducationtype',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='versionprofessiontype',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='versionspecialarea',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
    ]
