# Generated by Django 5.1.7 on 2025-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0043_alter_educationtype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'forename'], 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='versionperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person', 'verbose_name_plural': 'historical persons'},
        ),
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='forname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='surname'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='forname'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='surname'),
        ),
    ]
