# Generated by Django 5.1.7 on 2025-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0044_alter_person_options_alter_versionperson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='forename'),
        ),
        migrations.AlterField(
            model_name='versionperson',
            name='forename',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='forename'),
        ),
    ]
