# Generated by Django 5.1.7 on 2025-05-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0045_alter_person_forename_alter_versionperson_forename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versioneducationtype',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='versioninstitution',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='versionperson',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='versionplace',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='versionprofessiontype',
            name='version_tag',
        ),
        migrations.RemoveField(
            model_name='versionspecialarea',
            name='version_tag',
        ),
    ]
