# Generated by Django 5.1.7 on 2025-05-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0046_remove_versioneducationtype_version_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bornin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='collaborateswith',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='diedin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exilein',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='hasstudioin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='imprisonedin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='isinheritancein',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='isinventoriedin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='islearningat',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='ismemberof',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='livesin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='locatedin',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='worksas',
            options={'ordering': ['pk']},
        ),
    ]
