# Generated by Django 5.1.7 on 2025-05-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0047_alter_bornin_options_alter_collaborateswith_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['label'], 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='versionplace',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical place', 'verbose_name_plural': 'historical places'},
        ),
    ]
