# Generated by Django 5.1.7 on 2025-05-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0048_alter_place_options_alter_versionplace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['pk'], 'verbose_name': 'annotation', 'verbose_name_plural': 'annotations'},
        ),
    ]
