# Generated by Django 5.1.7 on 2025-05-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0049_alter_annotation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['label'], 'verbose_name': 'Institution', 'verbose_name_plural': 'Institutions'},
        ),
        migrations.AlterField(
            model_name='institution',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='versioninstitution',
            name='label',
            field=models.CharField(blank=True, default='', max_length=4096, verbose_name='label'),
        ),
    ]
