# Generated by Django 5.1.7 on 2025-06-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0051_annotation_fotographers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='fotographers',
            new_name='photographers',
        ),
    ]
