# Generated by Django 5.1.7 on 2025-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0052_rename_fotographers_annotation_photographers'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='warreporter',
            field=models.BooleanField(default=False),
        ),
    ]
