# Generated by Django 5.1.7 on 2025-06-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0053_annotation_warreporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
        migrations.AddField(
            model_name='versioninstitution',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
    ]
