# Generated by Django 5.1.7 on 2025-06-23 09:00

import apis_instance_nsvis.models
import django.db.models.deletion
import django_interval.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0056_personemployedatinstitution_personfoundsinstitution'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionLocatedInPlace',
            fields=[
                ('relation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='relations.relation')),
                ('end_date_to', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('end_date_from', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('end_date_sort', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('start_date_to', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('start_date_from', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('start_date_sort', models.DateField(auto_created=True, blank=True, editable=False, null=True)),
                ('start', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
                ('end', django_interval.fields.FuzzyDateParserField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
            bases=(apis_instance_nsvis.models.NsvisRelationMixin, 'relations.relation'),
        ),
    ]
