# Generated by Django 5.1.7 on 2025-06-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0057_institutionlocatedinplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='personemployedatinstitution',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='details'),
        ),
    ]
