# Generated by Django 5.1.7 on 2025-07-03 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0058_personemployedatinstitution_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='start',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='start_date_from',
            new_name='from_date_date_from',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='start_date_sort',
            new_name='from_date_date_sort',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='start_date_to',
            new_name='from_date_date_to',
        ),
    ]
