# Generated by Django 5.1.7 on 2025-07-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0059_rename_start_personemployedatinstitution_from_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='end',
            new_name='to_date',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='end_date_from',
            new_name='to_date_date_from',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='end_date_sort',
            new_name='to_date_date_sort',
        ),
        migrations.RenameField(
            model_name='personemployedatinstitution',
            old_name='end_date_to',
            new_name='to_date_date_to',
        ),
    ]
