# Generated by Django 5.2.5 on 2025-10-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0060_rename_end_personemployedatinstitution_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>', max_length=16, verbose_name='feature code'),
        ),
        migrations.AlterField(
            model_name='versionplace',
            name='feature_code',
            field=models.CharField(blank=True, default='', help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>', max_length=16, verbose_name='feature code'),
        ),
    ]
