# Generated by Django 5.2.5 on 2025-10-17 09:33

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0061_alter_place_feature_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionAnnotation',
            fields=[
                ('rootobject_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='apis_metainfo.rootobject')),
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('data', models.JSONField(editable=False, null=True)),
                ('image', models.TextField(editable=False, max_length=512)),
                ('issue', models.TextField(editable=False, max_length=256)),
                ('lst_task_id', models.IntegerField(editable=False)),
                ('lst_annotation_id', models.IntegerField(editable=False)),
                ('lst_result_id', models.TextField(editable=False, max_length=128)),
                ('author', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None)),
                ('caption', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('depicted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None)),
                ('location', models.TextField(blank=True, null=True)),
                ('topic', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), null=True, size=None)),
                ('other', models.TextField(blank=True, null=True)),
                ('internal_comment', models.TextField(blank=True, null=True)),
                ('photographers', models.JSONField(editable=False, null=True)),
                ('warreporter', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical annotation',
                'verbose_name_plural': 'historical annotations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
