# Generated by Django 5.2.6 on 2025-10-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0062_versionannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='ranking',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='versionannotation',
            name='ranking',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
