# Generated by Django 5.2.5 on 2026-03-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0064_versionbornin_versioncollaborateswith_versiondiedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine', models.CharField()),
                ('issue', models.CharField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MagazinePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origurl', models.URLField()),
                ('path', models.CharField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apis_instance_nsvis.magazineissue')),
            ],
        ),
    ]
