# Generated by Django 5.2.5 on 2026-03-24 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_instance_nsvis', '0065_magazineissue_magazinepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='magazine_page',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='apis_instance_nsvis.magazinepage'),
        ),
        migrations.AddField(
            model_name='versionannotation',
            name='magazine_page',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='apis_instance_nsvis.magazinepage'),
        ),
    ]
